library(dplyr)
library(stringr)
library(dlookr)
library(survey)
library(sqldf)
library(lessR)
library(plyr)
library(naniar)

# load NSDUH Workspace which contains PUF2017_100918
load("C:/Users/keogh/Desktop/Project/NSDUH_2017.RData")

NSDUH<- PUF2017_100918
summary(NSDUH)
head(NSDUH)
names(NSDUH)
colnames(NSDUH) <- toupper(colnames(NSDUH)) 
myvars <- c("QUESTID2","BOOKED","ABODALC","NEDHER","PNRNM30AL","PNRWYNORX","PNRWYGAMT","PNRWYOFTN","PNRWYLNGR","PNRWYOTWY","PNRNMLAS1","PNRRSMAIN","IRPNRANYREC","IRPNRNMREC","IROXCNNMYR","IRPNRNMINIT","IRPNRNMYFU","IRPNRNMAGE","TOBYR","TOBMON","ALCFLAG","ALCYR","ALCMON","MRJFLAG","MRJYR","MRJMON","COCFLAG","COCYR","COCMON","CRKFLAG","CRKYR","CRKMON","HERFLAG","HERYR","HERMON","HALLUCFLAG","HALLUCYR","HALLUCMON","INHALFLAG","INHALYR","INHALMON","METHAMFLAG","METHAMYR","METHAMMON","PNRANYFLAG","PNRANYYR","OXYCNANYYR","TRQANYFLAG","TRQANYYR","STMANYFLAG","STMANYYR","SEDANYFLAG","SEDANYYR","PSYANYFLAG","PSYANYYR","PNRNMFLAG","PNRNMYR","PNRNMMON","OXYCNNMYR","TRQNMFLAG","TRQNMYR","TRQNMMON","STMNMFLAG","STMNMYR","STMNMMON","SEDNMFLAG","SEDNMYR","SEDNMMON","PSYCHFLAG","PSYCHYR","PSYCHMON","OPINMYR","OPINMMON","HERPNRYR","ILLFLAG","ILLYR","ILLMON","MJONLYFLAG","MJONLYYR","MJONLYMON","ILLEMFLAG","ILLEMYR","ILLEMMON","CDUFLAG","DCIGMON","BNGDRKMON","HVYDRKMON","ILLANDALC","HYDCPDAPYU","ZOHYANYYR2","OXCOPDAPYU","TRAMPDAPYU","CODEPDAPYU","MORPPDAPYU","FENTPDAPYU","BUPRPDAPYU","OXYMPDAPYU","DEMEPDAPYU","HYDMPDAPYU","MTDNPDAPYU","PNROTANYR2","HYDCPDPYMU","OXCOPDPYMU","TRAMPDPYMU","CODEPDPYMU","MORPPDPYMU","FENTPDPYMU","BUPRPDPYMU","OXYMPDPYMU","DEMEPDPYMU","HYDMPDPYMU","MTDNPDPYMU","PNROTHPYMU2","PNRNDAYPM","FUPNRNM18","FUPNRNM21","PNRMAINRSN","SRCPNRNM2","SRCFRPNRNM","SRCCLFRPNR","GRSKMRJMON","GRSKMRJWK","GRSKCOCMON","GRSKCOCWK","GRSKHERTRY","GRSKHERWK","GRSKLSDTRY","GRSKLSDWK","GRSKBNGDLY","GRSKBNGWK","NDSSDNSP","DNICNSP","DEPNDALC","DEPNDMRJ","DEPNDCOC","DEPNDHER","DEPNDPYHAL","DEPNDPYINH","DEPNDPYMTH","DEPNDPYPNR","DEPNDPYTRQ","DEPNDPYSTM","DEPNDPYSED","DEPNDPYPSY","DEPNDPYILL","ABUSEALC","ABUSEMRJ","ABUSECOC","ABUSEHER","ABUSEPYHAL","ABUSEPYINH","ABUSEPYMTH","ABUSEPYPNR","ABUSEPYTRQ","ABUSEPYSTM","ABUSEPYSED","ABUSEPYPSY","ABUSEPYILL","ABUSEPYIEM","ABPYILLALC","ABPYILANAL","ABODMRJ","ABODCOC","ABODHER","UDPYHAL","UDPYINH","UDPYMTH","UDPYPNR","UDPYTRQ","UDPYSTM","UDPYSED","UDPYPSY","UDPYOPI","UDPYHRPNR","UDPYILL",
"NOBOOKY2","BKMVTHFT","BKLARCNY","BKBURGL","HERSMOK2","BKSRVIOL","BKSMASLT","BKROB","BKARSON","BKDRVINF","BKDRUNK","BKPOSTOB","BKDRUG","BKSEXNR","BKFRAUD","BKOTH","BKOTHOF2","DRVINALCO2","DRVINMARJ2","DRVINDRG","DRVINDROTMJ","DRVINALDRG","PAROL","PROB","TXEVRRCVD2","TXYRILL","TXLTYPNRL2","NMERTMT2","INHOSPYR","HRTCONDEV","COPDEVER","CIRROSEVR","HEPBCEVER","KIDNYDSEV","HIVAIDSEV","CANCEREVR","CABLADDER","CABLOLEULYM","CAOTHER2","CABREAST","CACERVIX","CACOLNRECT","CAESOPSTOM","CAGALLIVPAN","CAKIDNEY","CALARYLUNG","CAMELANOM","CAMOUTTHRO","CAOVARY","CAPROSTEST","CASKINOTH","CASKINDK","CATHYROID","CAUTERUS","CANCERYR","HRTCONDYR","HIGHBPMED","SNYSELL","SNYSTOLE","SNYATTAK","SPDMON","SPDYR","MHSUITHK","MHSUTK_U","MHSUIPLN","MHSUITRY","SMIYR_U","AMIYR_U","SMMIYR_U","MMIYR_U","LMIYR_U","LMMIYRU","MI_CAT_U","SMISUDPY","AMISUDPY","LMMISUDPY","AMDELT","AMDEYR","AMDETXRX","AMDERXO2","AMDEIMP","SEXIDENT","IRSEX","IRMARIT","IREDUHIGHST2","CATAGE","CATAG2","CATAG3","CATAG6","CATAG7","SEXAGE","NEWRACE2","SEXRACE","EDUHIGHCAT","HEALTH2","WRKSICKMO","WRKSKIPMO","IRWRKSTAT","IRWRKSTAT18","EDFAM18","IMOTHER","IFATHER","IRHHSIZ2","IRKI17_2","IRMCDCHP","IRMEDICR","IRCHMPUS","IRPRVHLT","IROTHHLT","IRINSUR4","IRFAMSOC","IRPINC3","IRFAMIN3","GOVTPROG","INCOME","POVERTY3","COUTYP4","ANALWT_C","VESTR","VEREP","ASDSOVL2","HERSMOKE","HRSMKREC","HERSNIFF","HRSNFREC","HERNEEDL","HEOTSMK","HEOTSNF","HEOTNDL","HEOTOTH","HEOTSP","HRNDLREC","AGE2", "RSKHERTRY", "RSKHERWK","YSDSOVRL")
NSD<- NSDUH[myvars]
summary(NSD)
head(NSD)
str(NSD)

NSD<-select (NSD,-c("PNRNM30AL","PNRWYNORX","PNRWYGAMT","PNRWYOFTN","PNRWYLNGR","PNRWYOTWY","PNRNMLAS1","PNRRSMAIN","IRPNRANYREC","IRPNRNMREC","IROXCNNMYR","IRPNRNMYFU","TOBYR","TOBMON","ALCFLAG","ALCYR","ALCMON","MRJFLAG","MRJMON","COCFLAG","COCMON","CRKFLAG","CRKMON","HALLUCFLAG","HALLUCMON","INHALFLAG","INHALMON","METHAMFLAG",
               "METHAMMON","TRQANYFLAG","STMANYFLAG","SEDANYFLAG","PSYANYFLAG","TRQNMMON","STMNMMON","SEDNMMON","PSYCHMON","ILLMON","MJONLYFLAG","MJONLYYR","MJONLYMON","ILLEMFLAG","ILLEMYR","ILLEMMON","CDUFLAG","DCIGMON","GRSKMRJMON","GRSKMRJWK","GRSKCOCMON",
               "GRSKCOCWK","GRSKLSDTRY","GRSKLSDWK","GRSKBNGDLY","GRSKBNGWK","DNICNSP","NOBOOKY2","BKMVTHFT","BKLARCNY","BKBURGL","BKSRVIOL","BKSMASLT","BKROB","BKARSON","BKDRVINF","BKDRUNK","BKPOSTOB","BKDRUG","BKSEXNR","BKFRAUD","BKOTH","BKOTHOF2","DRVINALCO2","DRVINMARJ2","DRVINDRG","DRVINDROTMJ","INHOSPYR","HRTCONDEV","COPDEVER","CIRROSEVR","KIDNYDSEV","CABLADDER","CABLOLEULYM","CAOTHER2","CABREAST","CACERVIX","CACOLNRECT","CAESOPSTOM","CAGALLIVPAN","CAKIDNEY","CALARYLUNG","CAMELANOM","CAMOUTTHRO","CAOVARY","CAPROSTEST","CASKINOTH",
               "CASKINDK","CATHYROID","CAUTERUS","HRTCONDYR","HIGHBPMED","MHSUITHK","MHSUTK_U","MHSUIPLN","MHSUITRY","SMIYR_U","AMIYR_U","SMMIYR_U","MMIYR_U","LMIYR_U","LMMIYRU","IREDUHIGHST2","IMOTHER",
               "IFATHER","IRHHSIZ2","IRKI17_2","IRFAMIN3","ABPYILLALC","ABPYILANAL","ABUSEPYIEM"))

NSD$YEAR<-2017 
summary(NSD)
glimpse(NSD)
head(NSD)
str(NSD)
View(NSD)

rm(PUF2017_100918)
rm(NSDUH)
rm(myvars)

NSD[,c("HERSMOKE","HEOTOTH","HEOTNDL","HEOTSMK","HERNEEDL","HEOTSNF","HRSNFREC")] <- list(NULL) # not required


# checking for missing variables - 24 observations of 4 variables
missing<-NSD%>%
  diagnose() %>%
  select(-unique_count, -unique_rate) %>% 
  filter(missing_count > 0) %>% 
  arrange(desc(missing_count))
View(missing)

sum(is.na(NSD))#498981
mean(is.na(NSD)) # first time 0.04642238

# Replace NA with -9 as 0 is used in some variables as a value
# Use -9 for NA where already in use in variable
NSD[c("DRVINALDRG","GRSKHERTRY","GRSKHERWK","SPDMON","SPDYR","LMMISUDPY","MI_CAT_U","AMDERXO2","AMDETXRX")][is.na(NSD[c("DRVINALDRG","GRSKHERTRY","GRSKHERWK","SPDMON","SPDYR","LMMISUDPY","MI_CAT_U","AMDERXO2","AMDETXRX")])] <- -9
NSD[c("ASDSOVL2","PAROL","PNRMAINRSN","POVERTY3","PROB","AMDEYR","AMISUDPY","AMDELT","AMDEIMP","HEALTH2","SMISUDPY","SRCCLFRPNR","SRCPNRNM2","YSDSOVRL","SRCFRPNRNM")][is.na(NSD[c("ASDSOVL2","PAROL","PNRMAINRSN","POVERTY3","PROB","AMDEYR","AMISUDPY","AMDELT","AMDEIMP","HEALTH2","SMISUDPY","SRCCLFRPNR","SRCPNRNM2","YSDSOVRL","SRCFRPNRNM")])] <- -9
sum(is.na(NSD))

# Change gender to zero and one for M/F
str(NSD$IRSEX)
NSD$IRSEX <- mapvalues(NSD$IRSEX,from=c(1,2), to=c(0,1))
str(NSD$IRSEX)
#NSD$IRSEX= as.factor(NSD$IRSEX) -changes to 2 and 1 with levels 0 and 1


# rechecking for missing variables -0
missing<-NSD%>%
  diagnose() %>%
  select(-unique_count, -unique_rate) %>% 
  filter(missing_count > 0) %>% 
  arrange(desc(missing_count))
rm(missing)

#dropping fields no longer reqd-discovered in tidying spss data
NSD<-select(NSD,-c("HERSMOKE","HRSNFREC","HERNEEDL","HEOTSMK","HEOTSNF","HEOTNDL","HEOTOTH"))

#Replacing values for Bad Data, Don't know, Refused, Skip with NA and then  0
# Easier here than in SPSS imported data
#99, 999, 9999 Legitimate Skip/NEVER MISUSED
#83 or 983, 9983, Did not use/misuse/Not a past year initiate
#85 or 985, 9985 Bad Data
#91 or 991 or 9991 Never used
# 93, 993, 9993 Did not use/not a past year initiate etc.
# 94, 994, 9994 Don't Know
# 97,997,9997 Refused
# 98, 998, 9998 Blank


#ran very slowly and was hanging so after a bit of testing did it in smaller chunks
#na_numbers<-c(83,983,9983,98, 998, 9998,99,999,9999,85,985,9985,91,991,9991,93,993,9993,94,994,9994,97,997,9997)
#NSD<-NSD%>%replace_with_na_all(condition = ~.x %in% na_numbers)
na_numbers<-c(83,91,94,99,999,983)
NSD<-NSD%>%replace_with_na_all(condition = ~.x %in% na_numbers)

na_numbers<-c(9983,98,998,9998)
NSD<-NSD%>%replace_with_na_all(condition = ~.x %in% na_numbers)

na_numbers<-c(9999,85,985,9985)
NSD<-NSD%>%replace_with_na_all(condition = ~.x %in% na_numbers)

na_numbers<-c(991,9991,93,993,9993)
NSD<-NSD%>%replace_with_na_all(condition = ~.x %in% na_numbers)

na_numbers<-c(994,9994,97,997,9997)
NSD<-NSD%>%replace_with_na_all(condition = ~.x %in% na_numbers)
NSD[is.na(NSD)] <- 0 
sum(is.na(NSD))

rm(na_numbers)
rm(newdf)
nsdbak<-NSD
#Sticking the two together till I decide which to drop
DR<-NSD
DS<-dfs
colnames(DR) <- paste(colnames(DR),"R", sep = "_")
colnames(DS) <- paste(colnames(DS),"S", sep = "_")

both <- sqldf("select * from DR inner join DS on DR.QUESTID2_R = DS.QUESTID2_S")
View(both)
df<-both[,sort(names(both))]
View(df)
View(names(df))
str(df, list.len=ncol(df))

write.csv(df, file = "joined.csv")


